export enum Role {
  SUPERIOR_AMIR = 'SUPERIOR_AMIR',
  VICE_AMIR = 'VICE_AMIR',
  SECRETARY = 'SECRETARY',
  EDUCATION_AMIR = 'EDUCATION_AMIR',
  COMMUNITY_AMIR = 'COMMUNITY_AMIR',
  ADMIN_AMIR = 'ADMIN_AMIR',
  FINANCE_AMIR = 'FINANCE_AMIR',
  PROGRAM_AMIR = 'PROGRAM_AMIR',
  SOCIAL_MEDIA_AMIR = 'SOCIAL_MEDIA_AMIR',
  FOLLOWER = 'FOLLOWER',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}
export enum Side { MEN = 'MEN', WOMEN = 'WOMEN' }
export enum ChatType {
  NINE_AMIR = 'NINE_AMIR', THREE_MAIN = 'THREE_MAIN',
  SUB_AMIR_GROUP = 'SUB_AMIR_GROUP', SMALL_AMIR_GROUP = 'SMALL_AMIR_GROUP',
  PUBLIC = 'PUBLIC', DIRECT = 'DIRECT',
}
export enum PlanStatus { PENDING = 'PENDING', IN_PROGRESS = 'IN_PROGRESS', COMPLETED = 'COMPLETED' }
export enum CashFlowType { CASH_IN = 'CASH_IN', CASH_OUT = 'CASH_OUT' }
