var fs = require('fs');
var dir = 'src/app/api/fix-followers';
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
var code = 'import { NextResponse } from ' + String.fromCharCode(39) + 'next/server' + String.fromCharCode(39) + '\n'
+ 'import { db } from ' + String.fromCharCode(39) + '@/lib/db' + String.fromCharCode(39) + '\n'
+ 'import { Role, ChatType } from ' + String.fromCharCode(39) + '@/lib/enums' + String.fromCharCode(39) + '\n'
+ '\n'
+ 'const SUB_AMIR_ROLES = [Role.EDUCATION_AMIR, Role.COMMUNITY_AMIR, Role.ADMIN_AMIR]\n'
+ 'const SMALL_AMIR_ROLES = [Role.FINANCE_AMIR, Role.PROGRAM_AMIR, Role.SOCIAL_MEDIA_AMIR]\n'
+ '\n'
+ 'const ROLE_TO_CHAT: Record<string, string> = {\n'
+ '  EDUCATION_AMIR: ' + String.fromCharCode(39) + 'Education Group' + String.fromCharCode(39) + ',\n'
+ '  COMMUNITY_AMIR: ' + String.fromCharCode(39) + 'Community Group' + String.fromCharCode(39) + ',\n'
+ '  ADMIN_AMIR: ' + String.fromCharCode(39) + 'Admin Group' + String.fromCharCode(39) + ',\n'
+ '  FINANCE_AMIR: ' + String.fromCharCode(39) + 'Finance Group' + String.fromCharCode(39) + ',\n'
+ '  PROGRAM_AMIR: ' + String.fromCharCode(39) + 'Program Group' + String.fromCharCode(39) + ',\n'
+ '  SOCIAL_MEDIA_AMIR: ' + String.fromCharCode(39) + 'Social Media Group' + String.fromCharCode(39) + ',\n'
+ '}\n'
+ '\n'
+ 'export async function GET() {\n'
+ '  try {\n'
+ '    const followers = await db.user.findMany({\n'
+ '      where: { role: Role.FOLLOWER, subAmirId: { not: null } },\n'
+ '      select: { id: true, side: true, subAmirId: true },\n'
+ '    })\n'
+ '\n'
+ '    let fixed = 0\n'
+ '    for (const f of followers) {\n'
+ '      const amir = await db.user.findUnique({ where: { id: f.subAmirId! }, select: { role: true } })\n'
+ '      if (!amir) continue\n'
+ '\n'
+ '      const chatIds: string[] = []\n'
+ '\n'
+ '      if (SUB_AMIR_ROLES.includes(amir.role)) {\n'
+ '        const chatName = ROLE_TO_CHAT[amir.role]\n'
+ '        if (chatName) {\n'
+ '          const chat = await db.chat.findFirst({ where: { name: chatName, type: ChatType.SUB_AMIR_GROUP, side: f.side }, select: { id: true } })\n'
+ '          if (chat) chatIds.push(chat.id)\n'
+ '        }\n'
+ '      } else if (SMALL_AMIR_ROLES.includes(amir.role)) {\n'
+ '        const chatName = ROLE_TO_CHAT[amir.role]\n'
+ '        if (chatName) {\n'
+ '          const chat = await db.chat.findFirst({ where: { name: chatName, type: ChatType.SMALL_AMIR_GROUP, side: f.side }, select: { id: true } })\n'
+ '          if (chat) chatIds.push(chat.id)\n'
+ '        }\n'
+ '        const adminChat = await db.chat.findFirst({ where: { name: ROLE_TO_CHAT.ADMIN_AMIR, type: ChatType.SUB_AMIR_GROUP, side: f.side }, select: { id: true } })\n'
+ '        if (adminChat) chatIds.push(adminChat.id)\n'
+ '      }\n'
+ '\n'
+ '      for (const chatId of chatIds) {\n'
+ '        await db.chatMember.upsert({\n'
+ '          where: { chatId_userId: { chatId, userId: f.id } },\n'
+ '          create: { chatId, userId: f.id },\n'
+ '          update: {},\n'
+ '        })\n'
+ '        fixed++\n'
+ '      }\n'
+ '    }\n'
+ '\n'
+ '    return NextResponse.json({ fixed, totalFollowers: followers.length })\n'
+ '  } catch (error) {\n'
+ '    return NextResponse.json({ error: String(error) }, { status: 500 })\n'
+ '  }\n'
+ '}\n';
fs.writeFileSync(dir + '/route.ts', code, 'utf8');
console.log('[OK] Created src/app/api/fix-followers/route.ts');
